### ISSUE TITLE
Add a license to this package. 

### ISSUE THREAD

**Issue by ormarom** [riccardone/UriTemplate#3]
Hi, 
In order to use this code and still be compliant with my company's policy,
I need this repo to have some license, like a Apache License for example. 

can you add an open source license to this repo please?

**Comment by marcinwieczorek4digit** [comment]
> Hi, In order to use this code and still be compliant with my company's policy, I need this repo to have some license, like a Apache License for example.
> 
> can you add an open source license to this repo please?

Yep - the license would be helpful, otherwise any usage or even contribution is too risky.

**Comment by riccardone** [comment]
Sure, I'll add it asap

**Comment by riccardone** [comment]
Closed by https://github.com/riccardone/UriTemplate/commit/7f1c8e6d361fe04c94eebac27e36cddc24e01c94
